id: P008049
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ872
  title: བརྡ་སྤྲོད་ངག་སྒྲོན་གྱི་འགྲེལ་པ་ཚིག་གསལ
  author: ''
  volumes:
    99da08e772d640ab9bc268f65bcdbe21:
      image_group_id: I1CZ933
      title: ''
      volume_number: 1
      total_pages: 154
ebook_metadata:
  title: བརྡ་སྤྲོད་ངག་སྒྲོན་གྱི་འགྲེལ་པ་ཚིག་གསལ
  author: ''
  sku: P008049
  cover: cover.jpg
  layers:
  - pagination
