id: I14590985
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T07:02:28+00:00'
last_modified: '2022-06-08T18:04:07.571354+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ872
  title: བརྡ་སྤྲོད་ངག་སྒྲོན་གྱི་འགྲེལ་པ་ཚིག་གསལ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4639':
      image_group_id: I1CZ933
      title: Volume 1 of brda sprod ngag sgron gyi 'grel pa tshig gsal
      total_pages: 154
      order: 1
      base_file: 4639.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
